# Dockerfile.streamlit

# Use the official Python image as a base image
FROM python:3.10.12

# Set the working directory in the container
WORKDIR /app

# Copy the necessary files into the container
COPY streamlit_app.py ./

# Install necessary Python packages
RUN pip install --no-cache-dir streamlit requests

# Expose the port that Streamlit will run on
EXPOSE 8501

# Command to run the Streamlit app
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501"]
