# Dockerfile.fastapi

# Use the official Python image as a base image
FROM python:3.10.12

# Set the working directory in the container
WORKDIR /app

# Copy the necessary files into the container
COPY fastapi_app.py ./
COPY linear_regression_model.pkl ./
COPY standard_scaler.pkl ./
COPY requirements.txt ./

# Install necessary Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that FastAPI will run on
EXPOSE 8000

# Command to run the FastAPI app
CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]
