# -*- coding: utf-8 -*-
"""fastapi_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NuKLswKDuZh3GaTEM7pmiItyhuwZ_K_
"""

# !pip install fastapi pydantic unicorn transformers







# fastapi_app.py

from fastapi import FastAPI
import joblib
import numpy as np
from pydantic import BaseModel

# FastAPI app instance
app = FastAPI()

# Load model and scaler
model = joblib.load("linear_regression_model.pkl")
scaler = joblib.load("standard_scaler.pkl")

# Define the request body for prediction
class PredictionRequest(BaseModel):
    features: list  # List of features

# Endpoint to handle prediction requests
@app.post("/predict/")
async def predict(request: PredictionRequest):
    # Prepare the input for the model
    input_data = np.array(request.features).reshape(1, -1)
    scaled_input = scaler.transform(input_data)
    prediction = model.predict(scaled_input)
    return {"prediction": prediction.tolist()}

