# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NuKLswKDuZh3GaTEM7pmiItyhuwZ_K_
"""

# !pip install fastapi pydantic unicorn transformers







# streamlit_app.py

import streamlit as st
import requests

# API URL (FastAPI should run on localhost:8000)
api_url = "http://fastapi:8000/predict/"

# Streamlit app layout
st.title('Model Prediction App')
st.write('Enter a list of floating-point features and click "Predict" to get the prediction.')

# Input form for features (list of floats)
features = st.text_input('Enter features as a comma-separated list (e.g., 1.2, 3.4, 5.6):')

# Convert the input string into a list of floats
if features:
    try:
        features_list = [float(x.strip()) for x in features.split(',')]
        st.write(f'Features: {features_list}')
    except ValueError:
        st.error("Please enter valid floating-point numbers separated by commas.")
else:
    features_list = []

# Predict button
if st.button('Predict'):
    if features_list:
        # Send the features to the FastAPI backend for prediction
        response = requests.post(api_url, json={"features": features_list})
        if response.status_code == 200:
            prediction = response.json()['prediction']
            st.write(f'The prediction is: {prediction[0]}')
        else:
            st.error(f"Error: {response.status_code} - {response.text}")
    else:
        st.error("Please enter the features before clicking 'Predict'.")

